name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: git checkout
    
    - name: Get next version
      uses: reecetech/version-increment@2023.4.1
      id: version
      
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        username: igzhang
        password: ${{ secrets.DOCKER_PWD }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: igzhang/chat_proxy_web:${{ steps.version.outputs.version }}
